### ISSUE TITLE
RangeError when setting EvaporateMorphingText.loopForever to false

### ISSUE THREAD

**Issue by OverLoadedBurden** [SirusCodes/morphing_text#5]
The title explains itself, worth noticing it happens no matter how manny times i changed the list.

```RangeError (index): Invalid value: Not in inclusive range .....```

Am on  ```morphing_text: ^1.0.0-nullsafety.1```

**Comment by SirusCodes** [comment]
Thanks for reporting the issue. Will try to fix it ASAP.

**Comment by SirusCodes** [comment]
Fixed in `1.0.1`
